version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
