version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      ktor:
        patterns: ["io.ktor*"]
      database:
        patterns: [ "org.jdbi*", "org.flyway*", "org.postgresql*" ]
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"