version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      helidon:
        patterns: ["io.helidon*"]
      database:
        patterns: [ "org.jdbi*", "org.flyway*", "org.postgresql*" ]
      jte:
        patterns: ["gg.jte*" ]
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"